language: erlang
otp_release:
- 17.4
before_install:
- git clone https://github.com/elixir-lang/elixir
- cd elixir
- git checkout v1.0.3
- cd ..
- make -C elixir
before_script: "export PATH=`pwd`/elixir/bin:$PATH"
sudo: false
script: "elixir /home/travis/build/jamoryhawkins/belvedere/test/belvedere_test.exs"
notifications:
  slack: realminc:rDwDl8LzkSDVwzG6aCfkI1op
